Remove PNG map and Markdown summary files for the 3 scenarios names
- ACM4p9_Capilano5 -> ACM4p9_GeorgiaStraitFault
- ACM7p4_BurwashLanding -> ACM7p4_DenaliFault
- SCM5p5_Ottawa -> SCM5p5_ConstanceBay

The following command was used to remove the obsolete files:

    git rm ACM4p9_Capilano5.* ACM7p4_BurwashLanding.* SCM5p5_Ottawa.*

Without their removal, finishedMap.sh would fail as follows:

    $ ../scripts/finishedMap.sh
    Traceback (most recent call last):
      File "OpenDRR/earthquake-scenarios/FINISHED/../scripts/generate_yml.py", line 35, in <module>
        config.read_file(open(f'../initializations/s_Hazard_{name}.ini'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '../initializations/s_Hazard_ACM4p9_Capilano5.ini'